\input texinfo
@c -*-texinfo-*-
@c Last changed Time-stamp: <2005-10-26 16:24:17 xtof>
@set revision $Id: libODES.texinfo,v 1.4 2005/10/26 14:25:08 chfl Exp $
@setfilename libODES.info
@settitle libODES
@ifclear Version
@set Version 1.6.0
@end ifclear
@iftex
@afourpaper
@end iftex
@ifinfo
@setchapternewpage odd
@end ifinfo
@titlepage
@sp 10
@title{libODES}
@sp
@subtitle{A Library for numerically solving ODEs}

@vskip 0pt plus 1filll
Copyright @copyright{2005} @author{Rainer Machne and Christoph Flamm}
@c @smallexample
Revision @value{revision}
@c @end smallexample
@end titlepage

@node Top, Introduction, (dir), (dir)
@comment node-name, next,          previous, up

@ifinfo
This file documents the libODES Version @value{Version}

Copyright @copyright{2005} Rainer Machne and Christoph Flamm
@end ifinfo

@menu
* Introduction::
* API Reference::
* Function Index::
* Variable Index::
* Datatype Index::
@end menu

@node Introduction, API Reference, Top, Top
@chapter Introduction

The core of the libODES is formed by a collection of routines for
basic algebraic and numerical treatment of systems of ordinary
differential equations (ODEs). These routines can be accessed through
stand-alone programs, such as @code{SBML_odeSolver} which should be
sufficient for most users. For those who wish to develop their own
programs we provide a library which can be linked to your own code.

This document only describes the library and will be primarily useful
to programmers. The stand-alone programs are described in separate man
pages. The latest version of the package including source code and
html versions of the documentation can be found at
@ifclear texi2html
@url{http://www.tbi.univie.ac.at/software/odeSolver/}.
@end ifclear
@ifset texi2html
@ifhtml
the <a href="http://www.tbi.univie.ac.at/software/odeSolver/">
libODES page</a>.
@end ifhtml
@end ifset
This manual documents version @value{Version}.

Please send comments and bug reports to
@ifclear texi2html
@email{odes@@tbi.univie.ac.at}.
@end ifclear
@ifset texi2html
@ifhtml
<a href="mailto:raim@tbi.univie.ac.at">
&lt;Rainer.Machne@tbi.univie.ac.at&gt;</a>.
<a href="mailto:xtof@tbi.univie.ac.at">
&lt;Christoph.Flamm@tbi.univie.ac.at&gt;</a>.
@end ifhtml
@end ifset

@node API Reference, Function Index, Introduction, Top
@comment  node-name,  next,  previous,  up
@chapter API Reference

Information is ordered by include header files of the libSOS.

@menu
* ASTIndexNameNode.h::
* commandLine.h::
* cvodedata.h::
* cvodedatatype.h::
* drawGraph.h::
* exportdefs.h::
* integratorInstance.h::
* integratorSettings.h::
* interactive.h::
* modelSimplify.h::
* odeConstruct.h::
* odemodeldatatype.h::
* odeModel.h::
* odeSolver.h::
* options.h::
* printModel.h::
* processAST.h::
* sbml.h::
* sbmlResults.h::
* solverError.h::
* util.h::
* variableIndex.h::
@end menu

@c +-----------------------------+
@c | begin of ASTIndexNameNode.h |
@node ASTIndexNameNode.h, commandLine.h, , API Reference
@section @file{ASTIndexNameNode.h}

Class @code{ASTIndexNameNode} is inherited from the libsbml class
@code{ASTNode} and adds the two private fields @code{index} and
@code{indexSet} to this class. It is intended to make the name lookup
fast, since the index relates the name of a species in an AST to its
concentration (position) in the @code{cvodeResults.values} array.

@subsection public class methodes
@deftypemethod ASTIndexNameNode void ASTIndexNameNode ()
Default constructor.
@end deftypemethod

@deftypemethod  ASTIndexNameNode {unsigned int} getIndex ()
Returns value of the object field @code{index}.
@end deftypemethod

@deftypemethod ASTIndexNameNode bool isSetIndex ()
Returns @code{true} if the object field @code{index} is set,
@code{false} otherwise
@end deftypemethod

@subsection private class data
@deftypeivar ASTIndexNameNode {unsigned int} index
Holdes index of species in the concentration array.
@end deftypeivar
@deftypeivar ASTIndexNameNode int indexSet
Flag to indicate if object field @code{index} is set.
@end deftypeivar
@c | end of ASTIndexNameNode.h |
@c +---------------------------+

@c +---------------+
@c | commandLine.h |
@node commandLine.h, cvodedata.h, ASTIndexNameNode.h, API Reference
@section @file{commandLine.h}
@c | commandLine.h |
@c +---------------+

@c +-------------+
@c | cvodedata.h |
@node cvodedata.h, cvodedatatype.h, commandLine.h, API Reference
@section @file{cvodedata.h}
@deftp {Data type} cvodeData_t {}
@example
struct @{
 odeModel_t*      @var{model};
 int              @var{nvalues};
 double*          @var{value};
 float            @var{currenttime};
 double**         @var{sensitivity};
 cvodeSettings_t* @var{opt};
 int*             @var{trigger};
 int              @var{steadystate};
 cvodeResults_t*  @var{results};
 int              @var{run}
@}
@end example
@var{model} is a pointer to the the model system.  @var{nvalues} is
the size of array @var{value} holding the values of all variables and
parameters of the model system.
@end deftp

@deftp {Data type} cvodeResults_t {}
@end deftp

@deftp {Data type} odeModel_t {}
@end deftp
@c | cvodedata.h |
@c +-------------+

@c +-----------------+
@c | cvodedatatype.h |
@node cvodedatatype.h, drawGraph.h, cvodedata.h, API Reference
@section @file{cvodedatatype.h}
@c | cvodedatatype.h |
@c +-----------------+

@c +-------------+
@c | drawGraph.h |
@node drawGraph.h, exportdefs.h, cvodedatatype.h, API Reference
@section @file{drawGraph.h}
@c | drawGraph.h |
@c +-------------+

@c +--------------+
@c | exportdefs.h |
@node exportdefs.h, integratorInstance.h, drawGraph.h, API Reference
@section @file{exportdefs.h}
@c | exportdefs.h |
@c +--------------+

@c +----------------------+
@c | integratorInstance.h |
@node integratorInstance.h, integratorSettings.h, exportdefs.h, API Reference
@section @file{integratorInstance.h}

@deftypefun {} {integratorInstance_t*} IntegratorInstance_create (odeModel_t* @var{om}, cvodeSettings_t* @var{opt}) 
Creates and returns a new @code{integratorInstance} structure. Reads
initial values from @var{om} (@code{odeModel} structure) and
integration settings from @var{opt} (@code{cvodeSettings}
structure). Two internal structures are create @code{cvodeData},
holding data to perform the integration of the next timstep and
@code{cvodeResults}, holding the integration output data for all
previous timesteps of the integration. In addition the structure
@code{cvodeSolver} is initialized.
@end deftypefun
@c | integratorInstance.h |
@c +----------------------+

@c +----------------------+
@c | integratorSettings.h |
@node integratorSettings.h, interactive.h, integratorInstance.h, API Reference
@section @file{integratorSettings.h}
@c | integratorSettings.h |
@c +----------------------+

@c +---------------+
@c | interactive.h |
@node interactive.h, modelSimplify.h, integratorSettings.h, API Reference
@section @file{interactive.h}
@c | interactive.h |
@c +---------------+

@c +-----------------+
@c | modelSimplify.h |
@node modelSimplify.h, odeConstruct.h, interactive.h, API Reference
@section @file{modelSimplify.h}
@c | modelSimplify.h |
@c +-----------------+

@c +----------------+
@c | odeConstruct.h |
@node odeConstruct.h, odemodeldatatype.h, modelSimplify.h, API Reference
@section @file{odeConstruct.h}
@c | odeConstruct.h |
@c +----------------+

@c +--------------------+
@c | odemodeldatatype.h |
@node odemodeldatatype.h, odeModel.h, odeConstruct.h, API Reference
@section @file{odemodeldatatype.h}
@c | odemodeldatatype.h |
@c +--------------------+

@c +------------+
@c | odeModel.h |
@node odeModel.h, odeSolver.h, odemodeldatatype.h, API Reference
@section @file{odeModel.h}
@c | odeModel.h |
@c +------------+

@c +-------------+
@c | odeSolver.h |
@node odeSolver.h, options.h, odeModel.h, API Reference
@section @file{odeSolver.h}
@c | odeSolver.h |
@c +-------------+

@c +-----------+
@c | options.h |
@node options.h, printModel.h, odeSolver.h, API Reference
@section @file{options.h}
@c | options.h |
@c +-----------+

@c +--------------+
@c | printModel.h |
@node printModel.h, processAST.h, options.h, API Reference
@section @file{printModel.h}
@c | printModel.h |
@c +--------------+

@c +--------------+
@c | processAST.h |
@node processAST.h, sbml.h, printModel.h, API Reference
@section @file{processAST.h}
@c | processAST.h |
@c +--------------+

@c +--------+
@c | sbml.h |
@node sbml.h, sbmlResults.h, processAST.h, API Reference
@section @file{sbml.h}
@c | sbml.h |
@c +--------+

@c +---------------+
@c | sbmlResults.h |
@node sbmlResults.h, solverError.h, sbml.h, API Reference
@section @file{sbmlResults.h}
@c | sbmlResults.h |
@c +---------------+

@c +---------------+
@c | solverError.h |
@node solverError.h, util.h, sbmlResults.h, API Reference
@section @file{solverError.h}
@c | solverError.h |
@c +---------------+

@c +--------+
@c | util.h |
@node util.h, variableIndex.h, solverError.h, API Reference
@section @file{util.h}
@c | util.h |
@c +--------+

@c +-----------------+
@c | variableIndex.h |
@node variableIndex.h, , util.h, API Reference
@section @file{variableIndex.h}
@c | variableIndex.h |
@c +-----------------+

@node Function Index, Variable Index, API Reference, Top
@unnumbered Function Index
@printindex fn

@node Variable Index, Datatype Index, Function Index, Top
@unnumbered Variable Index
@printindex vr

@node Datatype Index, , Variable Index, Top
@unnumbered Datatype Index
@printindex tp

@contents
@bye

@c End of file
