/*
  Last changed Time-stamp: <2005-05-26 12:56:10 raim>
  $Id: sbmlResults.h,v 1.1 2005/05/30 19:49:12 raimc Exp $
*/
#ifndef _SBMLRESULTS_H_
#define _SBMLRESULTS_H_

/* A simple structure containing variable names,
   and their time courses generated by simulation routines.
*/
typedef struct _TimeCourse {
  int timepoints;  /* number of timepoints, including initial
		      conditions (formerly known as `nout +1') */
  int num_val;     /* number of variables */
  char **names;    /* variable names */
  double **values; /* variable values  x:timepoints, y:num_val */
} *TimeCourse;

/* A simple structure that contains time courses - represented
   by the TimeCourse structure - for
   SBML structures, such as species, non-constant compartments
   and parameters and reaction fluxes.
*/
typedef struct _SBMLResults {
  
  int timepoints; /* number of timepoints for which results exist,
		     including initial conditions */
  double *time;

  /* concentration and variable parameter and compartment time series */
  TimeCourse species;       /* time courses for all species */  
  TimeCourse compartments;  /* time courses for all non-constant
			       compartments */
  TimeCourse parameters;    /* time courses for all non-constant
			     global parameters */
  /* flux time series */
  TimeCourse fluxes; 
  
} *SBMLResults;

SBMLResults
SBMLResults_create(Model_t *m, int timepoints);
void
SBMLResults_free(SBMLResults results);

#endif

/* End of file */
